project_id = "hnszakoakrhqmojshfvk"

[functions.send-push-notification]
verify_jwt = true

[functions.task-due-reminders]
verify_jwt = false

[functions.calendar-event-reminders]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.analyze-financial-document]
verify_jwt = false

[functions.analyze-letter]
verify_jwt = false

[functions.extract-our-financial-fields]
verify_jwt = false

[functions.create-letter-image]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.test-push-notification]
verify_jwt = false

[functions.send-overdue-reminders]
verify_jwt = false

[functions.send-daily-agenda]
verify_jwt = false

[functions.send-deadline-reminders]
verify_jwt = false

[functions.send-comment-notification]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.receive-email]
verify_jwt = false
